#:def ranksuffix(RANK)
   $:'' if RANK == 0 else '(' + ':' + ',:' * (RANK - 1) + ')'
#:enddef ranksuffix

#:set PRECISIONS = ['int', 'dp', 'logical']
#:set PREC_NAME = ['integer', 'real(dp)', 'logical']

#:set RANKS = range(1, 6)

#:def dimensions(RANK)
   $: ' dims, '
#:enddef dimensions

#:def dimensions_def(RANK)
   $:'' if RANK == 0 else '\n'.join(  ['integer, intent(in) :: dims(' + str(RANK) + ')'  ] )
#:enddef dimensions_def

#:def size_def(RANK)
   $:'' if RANK == 0 else '\n'.join(  ['integer :: sizes(' + str(RANK) + ')'  ] )
#:enddef size_def

#:def size_assign(RANK)
   $:'' if RANK == 0 else '\n'.join(  ['sizes(' + str(RANKI) + ') = size( array, ' + str( RANKI ) + " )" for RANKI in range( 1, RANK+1 ) ] )
#:enddef size_assign

#:def size_assigntg(RANK)
   $:'' if RANK == 0 else '\n'.join(  ['sizes(' + str(RANKI) + ') = size( tg_array%array, ' + str( RANKI ) + " )" for RANKI in range( 1, RANK+1 ) ] )
#:enddef size_assigntg

#:def dimensions_def_de(RANK)
   $:'' if RANK == 0 else '\n'.join(  ['integer :: dim_' + str(r) for r in range( 1, RANK+1 ) ] )
#:enddef dimensions_def_de

#:def dimensions_size_dp(RANK)
   $:'real(dims(1),dp)' + ' '.join(  [' * real(dims(' + str(r) + '),dp)'   for r in range( 2, RANK + 1 ) ] )
#:enddef dimensions_size_dp

#:def sizes_size_dp(RANK)
   $:'real(sizes(1),dp)' + ' '.join(  [' * real(sizes(' + str(r) + '),dp)'   for r in range( 2, RANK + 1 ) ] )
#:enddef sizes_size_dp

#:def dimensions_array_size(RANK)
   $:'1:dims(1)' + ' '.join(  [', 1:dims(' + str(r) + ')'   for r in range( 2, RANK + 1 ) ] )
#:enddef dimensions_array_size

#:def copy_ranges_dims(RANK)
   $:', '.join( ['1:min(dims(' + str(r) + '),tg_array%dims(' + str(r) + '))' for r in range( 1, RANK+1 ) ] )
#:enddef copy_ranges_dims

#:def copy_ranges_sizes(RANK)
   $:', '.join( ['1:min(dims(' + str(r) + '),sizes(' + str(r) + '))' for r in range( 1, RANK+1 ) ] )
#:enddef copy_ranges_sizes

#:def tmp_decl(RANK, PREC)
   #:if PREC == 'int'
      $:'integer, allocatable :: tmp' + ranksuffix(RANK)
   #:endif
   #:if PREC == 'dp'
      $:'real(dp), allocatable :: tmp' + ranksuffix(RANK)
   #:endif
   #:if PREC == 'logical'
      $:'logical, allocatable :: tmp' + ranksuffix(RANK)
   #:endif
#:enddef tmp_decl

! This file is generated by fypp from tg_memory_dims.fpp. Regenerate with:
!   fypp src/allocation/tg_memory_dims.fpp src/allocation/tg_memory.f90
! Do not hand-edit tg_memory.f90 directly; edit this template instead.
module tg_memory
   use kinds, only: dp
   use printing, only: print_parameter
   implicit none

   interface tg_alloc
      #:for PREC in PRECISIONS
         #:for RANK in RANKS
            module procedure tg_alloc_${RANK}$_${PREC}$
         #:endfor
      #:endfor
   end interface tg_alloc

   interface tg_dealloc
      #:for PREC in PRECISIONS
         #:for RANK in RANKS
            module procedure tg_dealloc_${RANK}$_${PREC}$
         #:endfor
      #:endfor
   end interface tg_dealloc

   interface tg_sync
      #:for PREC in PRECISIONS
         #:for RANK in RANKS
            module procedure tg_sync_${RANK}$_${PREC}$
         #:endfor
      #:endfor
   end interface tg_sync

   interface tg_allocate
      #:for PREC in PRECISIONS
         #:for RANK in RANKS
            module procedure tg_allocate_${RANK}$_${PREC}$
         #:endfor
      #:endfor
   end interface tg_allocate

   interface tg_deallocate
      #:for PREC in PRECISIONS
         #:for RANK in RANKS
            module procedure tg_deallocate_${RANK}$_${PREC}$
         #:endfor
      #:endfor
   end interface tg_deallocate

   #:for PREC in PRECISIONS
      #:for RANK in RANKS
         type tg_array_${RANK}$_${PREC}$
            #:if PREC == 'int'
               integer, allocatable :: array${ranksuffix(RANK) }$
               real(dp) :: size_type = 4.0_dp
            #:endif
            #:if PREC == 'dp'
               real(${PREC}$), allocatable :: array${ranksuffix(RANK) }$
               real(dp) :: size_type = 8.0_dp
            #:endif
            #:if PREC == 'logical'
               logical, allocatable :: array${ranksuffix(RANK) }$
               real(dp) :: size_type = 4.0_dp
            #:endif
            integer :: dims(${RANK}$) = 0
            integer :: used_dims(${RANK}$) = 0
            logical :: allocated = .false.
            character(64) :: name = "none"
         end type tg_array_${RANK}$_${PREC}$

      #:endfor
   #:endfor
contains

   !! tg_alloc/tg_dealloc operate on the tg_array_<rank>_<prec> wrapper types.
   !! tg_array%dims is the physical (allocated) capacity; tg_array%used_dims is
   !! the logical (requested) extent. Requesting a size that fits within the
   !! current capacity just updates used_dims and does not touch the physical
   !! allocation (no reallocation). Growing beyond capacity allocates a new
   !! buffer, copies the overlapping region of the old data across, and swaps
   !! it in via move_alloc, so existing contents survive a regrow.

   #:for PREC in PRECISIONS
      #:for RANK in RANKS

         subroutine tg_alloc_${RANK}$_${PREC}$ (tg_array, ${dimensions(RANK)}$memory_total, memory_max, rank, name)
            character(len=*), intent(in) :: name
            integer, intent(in) :: rank
            type(tg_array_${RANK}$_${PREC}$), intent(inout) :: tg_array
            real(dp), intent(inout) :: memory_total
            real(dp), intent(inout) :: memory_max
            ${dimensions_def(RANK) }$
            ${size_def(RANK) }$
            ${tmp_decl(RANK, PREC)}$

            real(dp) :: total_array_size
            real(dp) :: prev_array_size

            total_array_size = ${dimensions_size_dp(RANK) }$*tg_array%size_type

#ifdef _CHECK_ALLOCATE

            write (*, *) 'TGAllOC type ', name, ' on rank ', rank, &
               ' size ', total_array_size, ' bytes, allocated? ', &
               allocated(tg_array%array), ' current memory ', &
               memory_total/(1024.0_dp**2), ' Mb', &
               ' memory max ', memory_max, " bytes"

            if (allocated(tg_array%array)) then
               write (*, *) 'array ', name, ' has already been allocated'
               write (*, *) 'input dims   ', dims
               write (*, *) 'dims         ', tg_array%dims
               write (*, *) 'used_dims    ', tg_array%used_dims
            end if

#endif

            if (allocated(tg_array%array)) then
               ! Check the sizes currently to modify the memory
               ${size_assigntg(RANK)}$

#ifdef _CHECK_ALLOCATE
               write (*, *) 'found dims   ', sizes
               write (*, *) 'already dims ', tg_array%dims
#endif
               prev_array_size = ${sizes_size_dp(RANK) }$*tg_array%size_type
               if (any(dims > tg_array%dims)) then
                  ! Requested capacity exceeds what is physically allocated:
                  ! grow into a new buffer, preserving the overlapping data
                  allocate (tmp(${dimensions_array_size(RANK)}$))
                  tmp(${copy_ranges_dims(RANK)}$) = tg_array%array(${copy_ranges_dims(RANK)}$)
                  call move_alloc(tmp, tg_array%array)

                  memory_total = memory_total - prev_array_size + total_array_size
                  memory_max = max(memory_total, memory_max)

                  tg_array%used_dims = dims
                  tg_array%dims = dims
                  tg_array%allocated = .true.
                  tg_array%name = name

#ifdef _CHECK_ALLOCATE
                  write (*, *) 'regrowing (data-preserving) due to dim mismatch from request'
#endif
               else
                  tg_array%used_dims = dims
#ifdef _CHECK_ALLOCATE
                  write (*, *) 'not reallocating as capacity is sufficient for request'
#endif
               end if
               return
            end if

            allocate (tg_array%array(${dimensions_array_size(RANK)}$))

            memory_total = memory_total + total_array_size
            memory_max = max(memory_total, memory_max)

            tg_array%used_dims = dims
            tg_array%dims = dims
            tg_array%allocated = .true.
            tg_array%name = name

         end subroutine tg_alloc_${RANK}$_${PREC}$

      #:endfor
   #:endfor

   #:for PREC in PRECISIONS
      #:for RANK in RANKS

         subroutine tg_dealloc_${RANK}$_${PREC}$ (tg_array, memory_total, rank, name)
            character(len=*), intent(in) :: name
            integer, intent(in) :: rank
            type(tg_array_${RANK}$_${PREC}$), intent(inout) :: tg_array
            real(dp), intent(inout) :: memory_total
            integer :: i
            real(dp) :: number_of_elements
            real(dp) :: total_array_size

            if (.not. allocated(tg_array%array)) then
#ifdef _CHECK_ALLOCATE
               write (*, *) 'array ', name, ' has already been deallocated'
#endif
               return
            end if

            number_of_elements = 1.0_dp
            do i = 1, ${RANK }$
               number_of_elements = number_of_elements*real(size(tg_array%array, i), dp)
            end do

            total_array_size = number_of_elements*tg_array%size_type

#ifdef _CHECK_ALLOCATE

            write (*, *) 'TGDEAllOC type ', name, ' on rank ', rank, &
               ' size ', total_array_size, ' bytes, allocated? ', &
               allocated(tg_array%array), ' current memory ', &
               memory_total/(1024.0_dp**2), ' Mb'

#endif

            memory_total = memory_total - total_array_size

            deallocate (tg_array%array)
            tg_array%used_dims = 0
            tg_array%dims = 0
            tg_array%allocated = .false.

         end subroutine tg_dealloc_${RANK}$_${PREC}$

      #:endfor
   #:endfor

   !! tg_sync resyncs a tg_array's dims/used_dims/allocated bookkeeping (and the
   !! memory_total/memory_max ledger) from the actual current state of %array,
   !! for when external code has (re)allocated %array directly instead of going
   !! through tg_alloc/tg_dealloc - e.g. a subroutine that takes %array as a
   !! plain allocatable dummy argument and reallocates it itself. Call this
   !! right after such a call returns, before any further tg_alloc/tg_dealloc
   !! calls on the same tg_array (otherwise those would make decisions based on
   !! stale dims and could under- or over-count memory, or worse, believe a
   !! smaller physical buffer is still large enough).

   #:for PREC in PRECISIONS
      #:for RANK in RANKS

         subroutine tg_sync_${RANK}$_${PREC}$ (tg_array, memory_total, memory_max, name)
            character(len=*), intent(in) :: name
            type(tg_array_${RANK}$_${PREC}$), intent(inout) :: tg_array
            real(dp), intent(inout) :: memory_total
            real(dp), intent(inout) :: memory_max
            ${size_def(RANK)}$
            integer :: dims(${RANK}$)
            real(dp) :: prev_array_size
            real(dp) :: total_array_size

            ! Bytes currently accounted for under the pre-sync dims (0 if never allocated)
            prev_array_size = 0.0_dp
            if (any(tg_array%dims > 0)) then
               sizes = tg_array%dims
               prev_array_size = ${sizes_size_dp(RANK)}$*tg_array%size_type
            end if

            if (allocated(tg_array%array)) then
               ${size_assigntg(RANK)}$
               dims = sizes
               total_array_size = ${sizes_size_dp(RANK)}$*tg_array%size_type

               memory_total = memory_total - prev_array_size + total_array_size
               memory_max = max(memory_total, memory_max)

               tg_array%dims = dims
               tg_array%used_dims = dims
               tg_array%allocated = .true.

#ifdef _CHECK_ALLOCATE
               write (*, *) 'TGSYNC type ', name, ' resynced dims ', dims
#endif
            else
               memory_total = memory_total - prev_array_size
               tg_array%dims = 0
               tg_array%used_dims = 0
               tg_array%allocated = .false.

#ifdef _CHECK_ALLOCATE
               write (*, *) 'TGSYNC type ', name, ' array not allocated - reset to 0'
#endif
            end if

         end subroutine tg_sync_${RANK}$_${PREC}$

      #:endfor
   #:endfor

   !! tg_allocate/tg_deallocate are the bare-array equivalents of tg_alloc/tg_dealloc,
   !! for cases where wrapping the array in a tg_array_<rank>_<prec> derived type
   !! (and updating every call site that reads it) isn't warranted. They avoid
   !! reallocation the same way, but since there is no wrapper type to remember the
   !! "used" extent separately from the physical one, callers see the full physical
   !! capacity via size(array) - there is no equivalent of used_dims here.

   #:for PREC in PRECISIONS
      #:for RANK in RANKS

         subroutine tg_allocate_${RANK}$_${PREC}$ (array, ${dimensions(RANK)}$memory_total, memory_max, rank, name)
            character(len=*), intent(in) :: name
            integer, intent(in) :: rank
            #:if PREC == 'int'
               integer, allocatable, intent(inout) :: array${ranksuffix(RANK) }$
               real(dp), parameter :: size_type = 4.0_dp
            #:endif
            #:if PREC == 'dp'
               real(${PREC}$), allocatable, intent(inout) :: array${ranksuffix(RANK) }$
               real(dp), parameter :: size_type = 8.0_dp
            #:endif
            #:if PREC == 'logical'
               logical, allocatable, intent(inout) :: array${ranksuffix(RANK) }$
               real(dp), parameter :: size_type = 4.0_dp
            #:endif
            real(dp), intent(inout) :: memory_total
            real(dp), intent(inout) :: memory_max
            ${dimensions_def(RANK) }$
            ${size_def(RANK) }$
            ${tmp_decl(RANK, PREC)}$

            real(dp) :: total_array_size
            real(dp) :: prev_array_size

            total_array_size = ${dimensions_size_dp(RANK) }$*size_type

#ifdef _CHECK_ALLOCATE

            write (*, *) 'TGAllOC ', name, ' on rank ', rank, &
               ' size ', total_array_size, ' bytes, allocated? ', &
               allocated(array), ' current memory ', &
               memory_total/(1024.0_dp**2), ' Mb', &
               ' memory max ', memory_max, " bytes"

#endif

            if (allocated(array)) then
               ! Check the sizes currently to modify the memory
               ${size_assign(RANK)}$
               prev_array_size = ${sizes_size_dp(RANK) }$*size_type
               if (any(dims > sizes)) then
                  ! Grow into a new buffer, preserving overlapping data
                  allocate (tmp(${dimensions_array_size(RANK)}$))
                  tmp(${copy_ranges_sizes(RANK)}$) = array(${copy_ranges_sizes(RANK)}$)
                  call move_alloc(tmp, array)

                  memory_total = memory_total - prev_array_size + total_array_size
                  memory_max = max(memory_total, memory_max)
               end if
               return
            end if

            allocate (array(${dimensions_array_size(RANK)}$))

            memory_total = memory_total + total_array_size
            memory_max = max(memory_total, memory_max)

         end subroutine tg_allocate_${RANK}$_${PREC}$

      #:endfor
   #:endfor

   #:for PREC in PRECISIONS
      #:for RANK in RANKS

         subroutine tg_deallocate_${RANK}$_${PREC}$ (array, memory_total, rank, name)
            character(len=*), intent(in) :: name
            integer, intent(in) :: rank
            #:if PREC == 'int'
               integer, allocatable, intent(inout) :: array${ranksuffix(RANK) }$
               real(dp), parameter :: size_type = 4.0_dp
            #:endif
            #:if PREC == 'dp'
               real(${PREC}$), allocatable, intent(inout) :: array${ranksuffix(RANK) }$
               real(dp), parameter :: size_type = 8.0_dp
            #:endif
            #:if PREC == 'logical'
               logical, allocatable, intent(inout) :: array${ranksuffix(RANK) }$
               real(dp), parameter :: size_type = 4.0_dp
            #:endif
            real(dp), intent(inout) :: memory_total
            integer :: i
            real(dp) :: number_of_elements
            real(dp) :: total_array_size

            if (.not. allocated(array)) then
#ifdef _CHECK_ALLOCATE
               write (*, *) 'array ', name, ' has already been deallocated'
#endif
               return
            end if

            number_of_elements = 1.0_dp
            do i = 1, ${RANK }$
               number_of_elements = number_of_elements*real(size(array, i), dp)
            end do

            total_array_size = number_of_elements*size_type

#ifdef _CHECK_ALLOCATE

            write (*, *) 'TGDEAllOC ', name, ' on rank ', rank, &
               ' size ', total_array_size, ' bytes, allocated? ', &
               allocated(array), ' current memory ', &
               memory_total/(1024.0_dp**2), ' Mb'

#endif

            memory_total = memory_total - total_array_size

            deallocate (array)

         end subroutine tg_deallocate_${RANK}$_${PREC}$

      #:endfor
   #:endfor

   subroutine tg_print_memory(feature_name, total, max, rank)
      !! Optional per-feature memory report. Callers pass a memory_t's
      !! components directly, e.g. call tg_print_memory("neighbors", &
      !!    neighbors%memory%total, neighbors%memory%max, rank)
      character(len=*), intent(in) :: feature_name
      real(dp), intent(in) :: total
      real(dp), intent(in) :: max
      integer, intent(in) :: rank

      if (rank /= 0) return

      call print_parameter(trim(feature_name)//" mem (Mb)", total/(1024.0_dp**2))
      call print_parameter(trim(feature_name)//" mem max (Mb)", max/(1024.0_dp**2))

   end subroutine tg_print_memory

end module tg_memory
