# Copyright (c) 2020-2021 by Albert Bartók and Miguel Caro

# User-modifiable variables below

# Compiler, preprocessor directives, etc.
F90=mpif90
PP=-cpp -D _MPIF90
F90_MOD_DIR_OPT=-J

# Optimization flags (uncomment second option to enable debugging tools)
# F90_OPTS=-fPIC -O3 -march=native -ffast-math -funroll-loops -ffree-line-length-none
F90_OPTS=-fPIC -O0 -fcheck=bounds  -g -fcheck=all -ffree-line-length-none  #-D_DEBUG # -Wall

# BLAS and LAPACK libraries
LIBS=-lopenblas #lapack -lblas
#LAPACK_LIB_DIR=
#LIBS=-L$(LAPACK_LIB_DIR) -llapack -lblas
